
namespace SocialLearningGame.Logic
{
    public enum DataType
    {
        CURRENT_USER, CURRENT_GROUP, ALL_USERS, ALL_CATEGORIES, ALL_QUESTIONS, ALL_GROUPS, 
        ALL_GROUP_PLAYERS, ALL_USER_ANSWERED, ALL_GROUP_ANSWERED, ALL_NOTIFICATIONS, USER_INTERESTS, INVITED_USERS,

        POST_PROGRESS, CREATE_GROUP, DELETE_GROUP, LEAVE_GROUP, INVITE_PLAYER, DELETE_NOTIFICATION, ACCEPT_NOTIFICATION
    }
}
